name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:27.0
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Start Kafka with docker-compose
        run: |
          docker compose -f docker-compose.test.yml up -d
          echo "Waiting for Kafka..."
          sleep 20

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Kafka
        run: |
          for i in {1..30}; do
            nc -z localhost 9092 && echo "Kafka is up!" && exit 0
            sleep 2
          done
          echo "Kafka did not start in 60 seconds."
          exit 1

      - name: Run tests        
        run: export PYTHONPATH=$PWD && pytest -vv
          

      - name: Build Docker image
        run: docker build -t my-kafka-service:latest .
